spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://10.10.3.201:3306/crmdb?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          username: root
          password: Dev_0118
          driver-class-name: com.mysql.cj.jdbc.Driver