server:
  port: 9999
magic-api:
  # 配置web页面入口
  web: /magic/web
  resource:
    # 配置文件存储位置。当以classpath开头时，为只读模式
    # mac用户请改为可读写的目录
    #如果不想存到文件中，可以参考配置将接口信息存到数据库、Redis中（或自定义）
    location: D:/devloop/magic-api

spring:
  datasource:
    dynamic:
      primary: master # 设置默认的数据源或者数据源组,默认值即为master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://10.10.3.201:3306/crmdb?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          username: root
          password: Dev_0118
          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://127.0.0.1:3306/magic-api-test
#          username: root
#          password: abc@1234
#          driver-class-name: com.mysql.cj.jdbc.Driver